# Generated by Django 5.2.8 on 2025-11-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_camisetas'),
        ),
    ]
