# Generated by Django 5.2.8 on 2025-11-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_camiseta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_camisetas'),
        ),
    ]
